// <auto-generated />
using System;
using ECommerce.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerce.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804234600_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.API.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_OrderItem_UnitPrice", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("ECommerce.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockCode")
                        .IsUnique();

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Price", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Product_StockQuantity", "\"StockQuantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kablosuz Mouse",
                            Price = 249.90m,
                            StockCode = "SKU-001",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mekanik Klavye",
                            Price = 899.50m,
                            StockCode = "SKU-002",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 3,
                            Name = "27 inç Monitör",
                            Price = 4999.00m,
                            StockCode = "SKU-003",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            Name = "USB-C Hub",
                            Price = 349.00m,
                            StockCode = "SKU-004",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kablosuz Kulaklık",
                            Price = 1299.90m,
                            StockCode = "SKU-005",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 6,
                            Name = "Laptop Standı",
                            Price = 449.90m,
                            StockCode = "SKU-006",
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 7,
                            Name = "Full HD Webcam",
                            Price = 1149.00m,
                            StockCode = "SKU-007",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 8,
                            Name = "Geniş Mousepad",
                            Price = 199.50m,
                            StockCode = "SKU-008",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 9,
                            Name = "Taşınabilir SSD 1TB",
                            Price = 2399.00m,
                            StockCode = "SKU-009",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bluetooth Hoparlör",
                            Price = 1799.90m,
                            StockCode = "SKU-010",
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 11,
                            Name = "Laptop Çantası 15.6\"",
                            Price = 699.00m,
                            StockCode = "SKU-011",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sayısal Tuş Takımı",
                            Price = 549.00m,
                            StockCode = "SKU-012",
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("ECommerce.API.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.API.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.API.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
